<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class PageContentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $updated_at = $created_at = Carbon::now()->format('Y-m-d H:i:s');
        
        foreach( [
            
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'Let\'s Connect', 'pc_description' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet.</p>', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_2', 'pc_title' => 'Our Package', 'pc_description' => '', 'pc_order' => 2, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_3', 'pc_title' => 'Ice Breaker', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est,</p><p> qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, </p>', 'pc_order' => 3, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_4', 'pc_title' => 'Market Madness', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est,</p><p> qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, </p>', 'pc_order' => 4, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_5', 'pc_title' => 'How It Works', 'pc_description' => '', 'pc_order' => 5, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_6', 'pc_title' => 'Pick Your Package', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae aut odit aut fugit. </p>', 'pc_order' => 6, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_7', 'pc_title' => 'Add Users', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae aut odit aut fugit. </p>', 'pc_order' => 7, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_8', 'pc_title' => 'Create Event', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae aut odit aut fugit. </p>', 'pc_order' => 8, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_9', 'pc_title' => 'Play Games', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae aut odit aut fugit. </p>', 'pc_order' => 9, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOME', 'pc_section_id' => 'SECTION_10', 'pc_title' => 'Our Worldwide Users', 'pc_description' => '', 'pc_order' => 10, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            

            [ 'pc_page_key' => 'ABOUT_US', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'About Us', 'pc_description' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, </p>', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            /*[ 'pc_page_key' => 'ABOUT_US', 'pc_section_id' => 'SECTION_2', 'pc_title' => 'About Us', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspernSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur</p>', 'pc_order' => 2, 'created_at' => $created_at, 'updated_at' => $updated_at ],*/
            [ 'pc_page_key' => 'ABOUT_US', 'pc_section_id' => 'SECTION_3', 'pc_title' => 'Let\'s Connect', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern</p><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit</p>', 'pc_order' => 3, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'ABOUT_US', 'pc_section_id' => 'SECTION_4', 'pc_title' => 'How We Grow Together', 'pc_description' => '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern</p><p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit</p>', 'pc_order' => 4, 'created_at' => $created_at, 'updated_at' => $updated_at ],


            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'How It Works', 'pc_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_2', 'pc_title' => 'Following Steps', 'pc_description' => '', 'pc_order' => 2, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_3', 'pc_title' => 'Pick Your Package', 'pc_description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern', 'pc_order' => 3, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_4', 'pc_title' => 'Add Users', 'pc_description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern', 'pc_order' => 4, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_5', 'pc_title' => 'Create Event', 'pc_description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern', 'pc_order' => 5, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'HOW_IT_WORKS', 'pc_section_id' => 'SECTION_6', 'pc_title' => 'Play Games', 'pc_description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, piciatis unde omnis iste natus error sit vluptatem accusantium ao. Nemo enim ipsam voluptatem quiluptatem quia voluptas sit asperna voluptas sit aspern', 'pc_order' => 6, 'created_at' => $created_at, 'updated_at' => $updated_at ],


            [ 'pc_page_key' => 'PACKAGES', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'Our Packages', 'pc_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],


            [ 'pc_page_key' => 'FAQS', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'Frequently Asked Questions', 'pc_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],


            [ 'pc_page_key' => 'CONTACT_US', 'pc_section_id' => 'SECTION_1', 'pc_title' => 'Contact Us', 'pc_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'pc_order' => 1, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'CONTACT_US', 'pc_section_id' => 'SECTION_2', 'pc_title' => 'Contact Us', 'pc_description' => '', 'pc_order' => 2, 'created_at' => $created_at, 'updated_at' => $updated_at ],
            [ 'pc_page_key' => 'CONTACT_US', 'pc_section_id' => 'SECTION_3', 'pc_title' => 'Get In Touch', 'pc_description' => 'Feel free to drop us a line below!', 'pc_order' => 3, 'created_at' => $created_at, 'updated_at' => $updated_at ],

        ] as $data ) { 
            DB::table('page_content')->insert( $data );
        }
    }
}
